spring:
  application:
    name: PrioritiX

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: password

logging:
  level:
    org.springframework.web: DEBUG
    com.vtkr.prioritix: INFO
